name: my_bookly_clean_architecture
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
  assets:
    - assets/images/
