name: my_bookly_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
  assets:
    - assets/images/
